#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase0

# Plots produced by plotGeneration.py
rm -f ./*.pdf ./*.png

#------------------------------------------------------------------------------
